export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const SELECT_TODO = 'SELECT_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const EDIT_DONE_TODO = 'EDIT_DONE_TODO'
export const DONE_TODO = 'DONE_TODO'
export const UNDO_DONE = 'UNDO_DONE'
export const DELETE_DONE_TODO = 'DELETE_DONE_TODO'